name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Recreate Flutter project structure
        run: |
          mv pubspec.yaml pubspec.temp.yaml
          mv lib lib.temp
          mv assets assets.temp
          rm -rf android/ ios/ .idea/
          flutter create --project-name mark .
          rm -rf pubspec.yaml lib assets
          mv pubspec.temp.yaml pubspec.yaml
          mv lib.temp lib
          mv assets.temp assets
          
      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

