name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Clean Android build files
        run: rm -rf android/

      - name: Recreate Flutter project
        run: |
          cd ..
          mv svga_player_app temp_svga_player_app
          flutter create --platforms=android --no-pub --no-android-x-migration temp_svga_player_app
          cp -R temp_svga_player_app/android/ svga_player_app/android/
          cp -R svga_player_app/assets/ temp_svga_player_app/assets/
          mv temp_svga_player_app svga_player_app

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

